### ISSUE TITLE
Religiones mas representativas y procesar datos dentro de la parte 2

### ISSUE THREAD

**Issue by Hernan4444** [PUC-Infovis/syllabus#1]
Hola, por el título tengo las dos siguientes dudas:

1. En el Heatmap piden las 10 religiones con mayor representación pero en el dataset, solo hay 16 mayores religiones (si es que consideramos "Otros" y "Non-Religious" como dos religiones más). Es posible reducir la cantidad para que en verdad se aprecia cuales son las religiones con mayor representación??

2.  En la parte de visualización puede haber un poco de procesamiento de datos como agrupar las filas para luego generar los svg o realizar algún filtro? o en la parte de Preprocesar debería crear un archivo que está listo para ser abierto y transformado en svg en la parte 2?

Gracias de antemano.

Ps: Despues que respondan, cierro la issue o ustedes se encargan de cerrarla despues?

**Comment by fdoflorenzano** [comment]
1. Sí, es posible disminuir la cantidad de religiones que se muestren. Si crees que esto es necesario para lograr una mejor representación, puedes reducirla. Pero, como todo, recuerda documentar tu decisión. Además, fijaremos un **mínimo de seis religiones**, incluyendo a _Otros_ y _Non-religious_.

2. La idea es que no. Todo tipo de preprocesamiento debe ir en la primera parte, para limitar la segunda parte a la lectura y a la visualización. 

PS: nosotros cerraremos el _issue_, para saber si es que alguien más tiene alguna duda sobre este mismo tema.

**Comment by fgvenegas** [comment]
Pero por ejemplo si quiero asociar los colores a un continente, puedo extraer los nombres de los continentes de mi csv y manualmente asociarlos a un color?

**Comment by fdoflorenzano** [comment]
@fgvenegas Buena pregunta, eso contaría como parte de visualización y no como preprocesamiento de datos.

**Comment by fgvenegas** [comment]
Buenaa gracias!
