### ISSUE TITLE
[T02] Embellecimiento

### ISSUE THREAD

**Issue by fgvenegas** [PUC-Infovis/syllabus#10]
Hola, si quiero por ejemplo una navbar para que se vea mas bonita la página, puedo usar Bootsrap o debo hacerla a 'mano'? 

Gracias!

**Comment by fgvenegas** [comment]
Ojala me digan que si 😢 ya use tiempo en esto 😢

**Comment by fdoflorenzano** [comment]
Sí. 😃

**Comment by fgvenegas** [comment]
gracias ✨
