### ISSUE TITLE
Tildes y duda Stacked

### ISSUE THREAD

**Issue by fgvenegas** [PUC-Infovis/syllabus#11]
Hola!

* ¿Como puedo hacer comparación de strings si en el csv para el stacked vienen nombres de continentes con tilde y quiero filtrar 😨 ? 
* ¿En el Stacked Area Graph no me queda claro si debo incluir la población de la región o solo los practicantes de cada religión?

Gracias ✨

**Comment by fdoflorenzano** [comment]
¡Hola! Perdón por la demora.
- Se subió una versión donde eso debería arreglarse, si sigue mal es por _encoding_. Avísanos. 
- No debe incluir una barra con toda la población, la suma _stacked_ de las áreas forma la total. Sería redundante poner ambas.

**Comment by fgvenegas** [comment]
Gracias!
