### ISSUE TITLE
duda tarea 2 datasets

### ISSUE THREAD

**Issue by lileiva** [PUC-Infovis/syllabus#12]
Hola, se pueden modificar los datasets con scripts de python, ejemplo quiero que el heatmap se vea de la forma
religion, region, valor

saludos

**Comment by fdoflorenzano** [comment]
¡Hola!
Sí, está permitido. Aún así, los archivos están lo suficientemente simplificados para alimentarlos directamente a la visualización y mantiene suficiente semántica por si solo. Recomendamos hacerlo directamente con `JavaScript` en la lectura del archivo.

Esto siempre es algo a considerar en el trabajo con visualizaciones. Hay un _tradeoff_ entre el pre-procesamiento (que significa poder computacional) y la complejidad de lectura e interpretación de parte de la visualización (poder computacional en la vis). En este caso es más simple simplificarle la pega a la visualización, pero en muchos casos, una solución media debiese existir. Por ejemplo, en el contexto de aplicaciones _web_, los mismos archivos utilizados por la visualizaciones son usados por varios sub-sistemas de la aplicación. Entonces la existencia de un tipo de formato solo para el uso de la visualización pierde sentido. O no necesariamente archivos, pero _endpoints_ de una _API_. ¿Es mejor tener una dirección única para el uso de una vis o es mejor reutilizar existentes? 

Pero, sí. 😄
