### ISSUE TITLE
[T03] Dependencia de módulos

### ISSUE THREAD

**Issue by Hernan4444** [PUC-Infovis/syllabus#15]
Hola, para confirmar en el enunciado se dice:
>  Debe utilizar algún canal sobre el nodo para diferenciar aquellos módulos que no dependen de ningún otro, aquellos que sólo dependen de otros módulos y el resto.

Si tengo: 
🅰️  -> 🅱️ 
🗡  -> 🅱️ -> 🌵
Donde las flechas son la dependencia. Las categorías serían: 
1. aquellos módulos que no dependen de ningún otro:  🌵 
1. aquellos que sólo dependen de otros módulos:  serían 🅰️ 🗡 
1. El resto: 🅱️ 

Tengo la duda en particular con 🅱️ si se puede considerar de la segunda categoría 😅 ?

Gracias de antemano!

**Comment by fdoflorenzano** [comment]
¡Hola! 🅱️ correspondería a la tercera categoría por la existencia de una dependencia que le llega y una dependencia que sale.

**Comment by Hernan4444** [comment]
Gracias!! 😃 

Segunda pregunta 👀

Si paso el mouse por 🗡 , de debe dar enfases a 🅱️  **Y** 🌵  o solo a 🅱️ , en otras palabras, enfatizo al nodo hover y los nodos de quien dependo o de forma como recursiva enfatizar todos los nodos relaciones??

Y en el caso de pasar el mouse por 🅱️ , enfatizaría a 🅰️, 🗡  y 🌵 ??, o sea los que dependen del nodo y de quien el nodo depende? o solo de quien el nodo depende? (¿y descarto a los demás que dependen del nodo?)

Saludos! ✌️

**Comment by fdoflorenzano** [comment]
¡Hola! No es aplicar la clausura transitiva. Es simplemente enfatizar aquellos modulos relacionados directamente (en cualquier dirección), es decir, todos los que dependen directamente del módulo y aquellos del cual el módulo depende directamente. 

En tu ejemplo, si haces hover sobre 🅱️, se enfatizan todos, pero si es sobre 🗡, entonces solo 🅱️ Y 🗡.
