### ISSUE TITLE
Duda flechas

### ISSUE THREAD

**Issue by fgvenegas** [PUC-Infovis/syllabus#16]
Tengo una duda, segun el Json, D3 es el target de muchos nodos, pero no debería ser el source de muchos? Como para que tenga sentido con las flechas 🤔 

Gracias!

**Comment by fdoflorenzano** [comment]
Es un tema semántico. Como dice el enunciado, modelaremos la dirección como: si v depende de u, entonces (u, v) pertenece al grafo. Así, las aristas en cierto sentido representan la dirección de complejidad de módulos. Los más basicos, son la fuente de varias aristas. Pero los más complejos, como d3 que encapsula muchos modulos, son el destino de aristas.

Uno también puede argumentar porque el lado contrario tiene sentido. Puedes abstraerte de eso y simplemente seguir el sentido que provee el dataset 😄. No te preocupes.

**Comment by fgvenegas** [comment]
Vale gracias!

**Comment by Hernan4444** [comment]
> Puedes abstraerte de eso y simplemente seguir el sentido que provee el dataset 😄. No te preocupes.

Si ya no me abstraje de eso, ¿lo cambio o lo dejo así?

Saludos ✌️

**Comment by fdoflorenzano** [comment]
TODOS APUNTAN A `D3.js`
