### ISSUE TITLE
Duda devDependencies

### ISSUE THREAD

**Issue by cglevican** [PUC-Infovis/syllabus#17]
Hola, a qué se refiere el atributo devDependencies? No entiendo el fragmento:
Debe utilizar algún canal sobre las aristas para diferenciar devDependencies
de dependencies regulares (o más bien, dependencias que no son devDepen-
dencies).

**Comment by fdoflorenzano** [comment]
¡Hola!

Como explicamos en ayudantía, la información de las dependencias y módulos se obtuvo de los repositorios públicos de cada módulo. Las dependencias en particular, nos basamos en los archivos `package.json` de cada módulo. En este archivo, se especifican dos tipos de dependencias: `dependencies` y `devDependencies`. Los detalles no son realmente importantes para nuestra aplicación, pero puedes pensarlos como un atributo categórico para dependencias: o son `devDependencies` o son `dependencies` (regulares). Para saber más detalles de las diferencias reales, puedes revisar el siguiente enlace sobre: [`package.json`](https://docs.npmjs.com/files/package.json). Para saber si una dependencia es una `devDependencie` con el campo `dev` de los `links` en el _dataset_.

¡Saludos!
