### ISSUE TITLE
Codebook distinto a los datos

### ISSUE THREAD

**Issue by fgvenegas** [PUC-Infovis/syllabus#2]
En el codebook, en el formato del CSV religional, mencionan la columna 'region' y en esa mencionan que una de las posibles regiones es Oceanía, pero en el CSV ninguno de los datos que hay es de la region de Oceanía, es normal que no hayan, osea es como parte de la tarea o el codebook no esta actualizado?

**Comment by fgvenegas** [comment]
Solucionado(?)

**Comment by fgvenegas** [comment]
Otra duda, puedo asumir que en el datase regional, la info de los continentes esta completa? Por ejemplo que la info de África no le falta la info de ningun pais de África?

**Comment by fdoflorenzano** [comment]
Sí, puedes.

**Comment by fdoflorenzano** [comment]
Sí, puedes. Probablemente no tiene la información actualizada en detalle, pero en datos agregados puedes asumir completitud.

**Comment by fgvenegas** [comment]
Otra duda que me surgió, para el heatmap por ejemplo, debemos trabajar solo con la información de las religiones de 2010?

**Comment by fdoflorenzano** [comment]
Sí! Trabaja con el año más reciente para el heatmap.

**Comment by fgvenegas** [comment]
okaa!
