### ISSUE TITLE
Exactitud Graficos

### ISSUE THREAD

**Issue by Hernan4444** [PUC-Infovis/syllabus#3]
Al momento de graficar, ¿puede pasar que el grafico no represente 100% el numero?
Esto lo digo porque con datos muy grandes es necesario realizar un ajuste para llevarlos a una escala que se permita trabajar en terminos de pixeles pero cuando hago eso se pierde un poco de la precisión (por las divisiones y multiplicaciones que involucran float) ¿Aceptarán eso o es necesario corregirlo?

Gracias de antemano.

**Comment by fdoflorenzano** [comment]
Escalamiento de datos es algo muy recurrente en visualización de información y es completamente valido emplearlo para una mejor representación. La perdida de precisión es finalmente un problema computacional inevitable. Mientras la transformación no altere dramáticamente la percepción de los datos, es valido.
