### ISSUE TITLE
Datos página COR

### ISSUE THREAD

**Issue by ironcadiz** [PUC-Infovis/syllabus#4]
Se puede usar el dataset de [COR](http://www.correlatesofwar.org/data-sets/cow-country-codes) que contiene la relación entre los códigos de los países y el nombre de los países  que usaron para hacer dataset de las religones?

Saludos!

**Comment by fdoflorenzano** [comment]
Sí, pueden usar datasets externos que los ayude con el procesamiento, mientras no reemplacen a los datos entregados claro.
