### ISSUE TITLE
Informe Tarea 01

### ISSUE THREAD

**Issue by Hernan4444** [PUC-Infovis/syllabus#5]
Que tiene que ir en el infome? Bajo mi interpretación seria algo como una pagina que muestre todos los gráficos y explicarlos pero no sé si esperan otra cosa como explicar el proceso para generar ese gráfico

Saludos!!

**Comment by fdoflorenzano** [comment]
Hola. El informe debiese mostrar los resultados de sus visualizaciones embebidas con párrafos de explicación explicando el proceso, decisiones tomadas, simplificaciones, etc... No se espera sea tan largo, pueden ser 2 o 3 oraciones por tipo de visualización. (Esto entiéndase el informe de la segunda parte de la tarea, el informe de la primera parte es similar, pero solo sobre el proceso de procesamiento de datos)
