### ISSUE TITLE
Parejas Proyecto

### ISSUE THREAD

**Issue by Hernan4444** [PUC-Infovis/syllabus#6]
Esta issue es para inscribir las parejas (Idea de @fdoflorenzano)

- Hernán Valdivieso y Freddie Venegas

**Comment by dacasas** [comment]
- Alex Arenas y Diego Casas

**Comment by crabarca** [comment]
- Andrés Espinosa y Cristóbal Abarca

**Comment by Vince-Valence** [comment]
+ Daniela Flores y Vicente Valencia

**Comment by izinman** [comment]
Isaac Zinman y Luis Leiva

**Comment by jecastro2** [comment]
Arturo del Real y  Juan Enrique Castro

**Comment by ChrisAMS** [comment]
Christian Meléndez y Andrés Cádiz

**Comment by sebamenabar** [comment]
Sebastián Amenábar y Raimundo Manterola

**Comment by cglevican** [comment]
Vicente Dominguez y Constanza Levican
