### ISSUE TITLE
Sobre la base de datos 

### ISSUE THREAD

**Issue by cglevican** [PUC-Infovis/syllabus#8]
1. Es obligatorio resumir las bases de datos en un archivo o se puede crear uno por pregunta?
2. Western Hemisphere = América? Según algunas páginas sí.

**Comment by fdoflorenzano** [comment]
1. Se pueden hacer múltiples archivos de salida luego del pre-procesamiento.
2. ¿Por qué exactamente la pregunta? Sí es para asignar los distintos continentes, reporta cual fue la distribución que asumiste.

**Comment by cglevican** [comment]
2. Sí es para usar esos datos para la pregunta 1 (Heatmap)
