### ISSUE TITLE
[T02] Precision Población

### ISSUE THREAD

**Issue by Hernan4444** [PUC-Infovis/syllabus#9]
Para el HeatMap se solicita mostrar de la población para cada religión. Considerando que los números son muy grandes (en terminos de magnitud y de cantidad de dígitos) ¿Es posible aproximarlo o expresarlos en alguna escala diferentes (como por cientos de personas o miles de personas)?  

Siento que poner todos los números podría hacer más ruido que aportar, pero llevandolos a una escala diferente se podría ver mejor auanque el costo sería perder precision con la población exacta.

Gracias de antemano!

**Comment by fdoflorenzano** [comment]
¡Hola! Sí, es posible. Es más, es muy recomendable lo hagan así. El formato de escritura de valores en una visualización siempre es una decisión importante, ya que es la forma que el usuario percibe estás cantidades. Como dices, numero así de grandes solo logran marear y no permiten apreciar mejor la relación entre poblaciones distintas. Generalmente nos limitamos a usar los datos directos provenientes del dataset, pero el formato siempre hay que tenerlo encuenta.

Te dejo [d3.format](https://github.com/d3/d3-format), que tiene varios métodos de formateo es bastante flexible.
